const fs=require('fs'),cp=require('child_process'),path=require('path'),crypto=require('crypto'),zlib=require('zlib'),{pathToFileURL}=require('url');
const edge=['C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Microsoft/Edge/Application/msedge.exe'].find(fs.existsSync);
if(!edge){console.error('Edge not found');process.exit(2)}
// Canonical logical-canvas visual parity. Batches 09–12 share the current shell and
// must be byte-identical. Legacy batches 01–08 may differ only by subpixel font
// hinting after CSS scoping; those use tight pixel-error limits plus exact DOM/geometry QA.
const defaults=[1,5,10,20,21,25,30,40,41,45,50,52,53,60,61,70,78,80,81,85,89,90,91,96,99,100,101,102,106,110,111,114,118,120];
const requested=process.argv.slice(2).map(Number).filter(n=>Number.isInteger(n)&&n>=1&&n<=120),samples=requested.length?requested:defaults;
const harness=pathToFileURL(path.resolve('qa_visual_parity_harness.html')).href;
function srcFor(n){return n<=20?'prototype_01_02_v2.html':n<=40?'prototype_03_04_v2.html':n<=60?'prototype_05_06_v2.html':n<=80?'prototype_07_08_v2.html':n<=100?'prototype_09_10_v2.html':'prototype_11_12_v2.html'}
function render(file,slide,out){const url=`${harness}?target=${encodeURIComponent(file)}&slide=${slide}`;const r=cp.spawnSync(edge,['--headless=new','--disable-gpu','--hide-scrollbars','--allow-file-access-from-files','--window-size=1600,900','--virtual-time-budget=2200',`--screenshot=${path.resolve(out)}`,url],{stdio:'pipe'});if(r.status!==0||!fs.existsSync(out))throw new Error(`render failed ${file} ${slide}`)}
function hash(file){return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')}
function paeth(a,b,c){const p=a+b-c,pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c}
function decode(file){const b=fs.readFileSync(file);if(b.subarray(0,8).toString('hex')!=='89504e470d0a1a0a')throw new Error('not png');let off=8,w,h,type,depth,interlace,id=[];while(off<b.length){const len=b.readUInt32BE(off),name=b.toString('ascii',off+4,off+8),d=b.subarray(off+8,off+8+len);if(name==='IHDR'){w=d.readUInt32BE(0);h=d.readUInt32BE(4);depth=d[8];type=d[9];interlace=d[12]}if(name==='IDAT')id.push(d);if(name==='IEND')break;off+=12+len}if(depth!==8||interlace!==0||![0,2,6].includes(type))throw new Error('unsupported png');const ch=type===6?4:type===2?3:1,stride=w*ch,raw=zlib.inflateSync(Buffer.concat(id)),out=Buffer.alloc(stride*h);let src=0;for(let y=0;y<h;y++){const f=raw[src++],row=raw.subarray(src,src+stride),dst=out.subarray(y*stride,(y+1)*stride),prev=y?out.subarray((y-1)*stride,y*stride):null;for(let x=0;x<stride;x++){const v=row[x],a=x>=ch?dst[x-ch]:0,bb=prev?prev[x]:0,c=prev&&x>=ch?prev[x-ch]:0;dst[x]=(f===0?v:f===1?v+a:f===2?v+bb:f===3?v+Math.floor((a+bb)/2):f===4?v+paeth(a,bb,c):0)&255}src+=stride}return{w,h,type,ch,data:out}}
function rgba(img,i){if(img.type===6)return[img.data[i*4],img.data[i*4+1],img.data[i*4+2],img.data[i*4+3]];if(img.type===2)return[img.data[i*3],img.data[i*3+1],img.data[i*3+2],255];const v=img.data[i];return[v,v,v,255]}
function pixelDiff(aFile,bFile){const a=decode(aFile),b=decode(bFile);if(a.w!==b.w||a.h!==b.h)throw new Error('size mismatch');let changed=0,c5=0,c20=0,sum=0;const n=a.w*a.h;for(let i=0;i<n;i++){const aa=rgba(a,i),bb=rgba(b,i);let d=0;for(let c=0;c<4;c++){const q=Math.abs(aa[c]-bb[c]);sum+=q;d=Math.max(d,q)}if(d>0)changed++;if(d>5)c5++;if(d>20)c20++;}return{changedPct:changed/n*100,changed5Pct:c5/n*100,changed20Pct:c20/n*100,meanAbs:sum/(n*4)}}
let failed=false;
for(const n of samples){const src=srcFor(n),a=`qa_parity_src_${n}.png`,b=`qa_parity_master_${n}.png`;render(src,n,a);render('index.html',n,b);const exact=hash(a)===hash(b),d=exact?{changedPct:0,changed5Pct:0,changed20Pct:0,meanAbs:0}:pixelDiff(a,b);const legacyPass=n<=80&&d.changedPct<=1.25&&d.changed5Pct<=1.05&&d.changed20Pct<=.8&&d.meanAbs<=.2;const pass=exact||legacyPass;console.log(`${n} ${src} pass=${pass} exact=${exact} changed=${d.changedPct.toFixed(4)}% >5=${d.changed5Pct.toFixed(4)}% >20=${d.changed20Pct.toFixed(4)}% mean=${d.meanAbs.toFixed(4)}`);if(!pass)failed=true;}
if(failed)process.exit(1);
